// This file is automatically generated by Visual Studio when you design the form visually
// It contains all the code that creates and positions the buttons, labels and textboxes
// You should not edit this file manually as Visual Studio will overwrite your changes

namespace SecureVault
{
    partial class LoginForm
    {
        // This variable keeps track of all the components on the form
        // so they can be properly cleaned up when the form closes
        private System.ComponentModel.IContainer components = null;

        // This method runs automatically when the form is closed
        // It frees up any memory or resources the form was using
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        // This method sets up all the visual elements on the form
        // such as where each control is positioned and how big it is
        private void InitializeComponent()
        {
            // Create each control that appears on the form
            this.lblPassword = new System.Windows.Forms.Label();
            this.txtPassword = new System.Windows.Forms.TextBox();
            this.btnLogin = new System.Windows.Forms.Button();

            // Temporarily pause the layout engine while we set everything up
            // This prevents the form from trying to redraw itself mid-setup
            this.SuspendLayout();
            // ---- Password Label ----
            // This is the text that says "Master Password" next to the input box
            this.lblPassword.AutoSize = true;
            this.lblPassword.Location = new System.Drawing.Point(30, 30);
            this.lblPassword.Name = "lblPassword";
            this.lblPassword.Size = new System.Drawing.Size(87, 13);
            this.lblPassword.TabIndex = 0;
            this.lblPassword.Text = "Master Password";

            // ---- Password TextBox ----
            // This is the box where the user types their master password
            // UseSystemPasswordChar = true means it shows dots instead of letters
            this.txtPassword.Location = new System.Drawing.Point(130, 27);
            this.txtPassword.Name = "txtPassword";
            this.txtPassword.Size = new System.Drawing.Size(180, 20);
            this.txtPassword.TabIndex = 1;
            this.txtPassword.UseSystemPasswordChar = true;

            // ---- Login Button ----
            // This is the button the user clicks to attempt login
            this.btnLogin.Location = new System.Drawing.Point(130, 65);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.Size = new System.Drawing.Size(75, 25);
            this.btnLogin.TabIndex = 2;
            this.btnLogin.Text = "Login";
            this.btnLogin.UseVisualStyleBackColor = true;
            // Wire up the click event so pressing the button calls btnLogin_Click
            // in LoginForm.cs
            this.btnLogin.Click += new System.EventHandler(this.btnLogin_Click);

            // ---- Form Settings ----
            // AcceptButton means pressing Enter on the keyboard triggers the login button
            this.AcceptButton = this.btnLogin;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;

            // Set the overall size of the login window
            this.ClientSize = new System.Drawing.Size(350, 120);

            // Add all the controls to the form so they actually appear
            this.Controls.Add(this.btnLogin);
            this.Controls.Add(this.txtPassword);
            this.Controls.Add(this.lblPassword);

            // FixedDialog means the window cannot be resized or maximised
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "LoginForm";

            // CenterScreen means the window appears in the middle of the screen
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Login";
            // Resume the layout engine now that everything is set up
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        // Declare the controls as private fields so they can be accessed
        // from anywhere in the LoginForm class
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Button btnLogin;
    }
}
