// This file is automatically generated by Visual Studio when you design the form visually
// It creates and positions all the buttons, labels, textboxes and the password list
// Do not edit this file manually as Visual Studio will overwrite your changes

namespace SecureVault
{
    partial class MainForm
    {
        // Keeps track of all components so they can be cleaned up when the form closes
        private System.ComponentModel.IContainer components = null;
        // Runs automatically when the form closes to free up memory
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Create all the controls that appear on the main vault screen
            txtSite = new TextBox();
            txtUsername = new TextBox();
            txtPassword = new TextBox();
            btnAdd = new Button();
            btnView = new Button();
            btnChangePassword = new Button();
            listBoxPasswords = new ListBox();
            lblSite = new Label();
            lblUsername = new Label();
            lblPassword = new Label();
            btnDelete = new Button();

            // Pause layout while we set everything up
            SuspendLayout();
            // ---- Site TextBox ----
            // Where the user types the website address for a new entry
            txtSite.Location = new Point(95, 25);
            txtSite.Name = "txtSite";
            txtSite.Size = new Size(180, 23);
            txtSite.TabIndex = 0;

            // ---- Username TextBox ----
            // Where the user types the username for a new entry
            txtUsername.Location = new Point(95, 55);
            txtUsername.Name = "txtUsername";
            txtUsername.Size = new Size(180, 23);
            txtUsername.TabIndex = 1;

            // ---- Password TextBox ----
            // Where the user types the password for a new entry
            // UseSystemPasswordChar = true means it shows dots instead of letters
            txtPassword.Location = new Point(95, 85);
            txtPassword.Name = "txtPassword";
            txtPassword.Size = new Size(180, 23);
            txtPassword.TabIndex = 2;
            txtPassword.UseSystemPasswordChar = true;

            // ---- Add Entry Button ----
            // Clicking this saves the new entry to the vault
            btnAdd.Location = new Point(95, 123);
            btnAdd.Name = "btnAdd";
            btnAdd.Size = new Size(55, 55);
            btnAdd.TabIndex = 3;
            btnAdd.Text = "Add Entry";
            btnAdd.UseVisualStyleBackColor = true;
            btnAdd.Click += btnAdd_Click;

            // ---- View Entry Button ----
            // Clicking this shows the selected entry after re-authentication
            btnView.Location = new Point(156, 123);
            btnView.Name = "btnView";
            btnView.Size = new Size(58, 55);
            btnView.TabIndex = 4;
            btnView.Text = "View Entry";
            btnView.UseVisualStyleBackColor = true;
            btnView.Click += btnView_Click;

            // ---- Change Master Password Button ----
            // Clicking this opens the change password form
            btnChangePassword.Location = new Point(95, 184);
            btnChangePassword.Name = "btnChangePassword";
            btnChangePassword.Size = new Size(180, 25);
            btnChangePassword.TabIndex = 5;
            btnChangePassword.Text = "Change Master Password";
            btnChangePassword.UseVisualStyleBackColor = true;
            btnChangePassword.Click += btnChangePassword_Click;

            // ---- Password List Box ----
            // This shows the list of saved site names on the right side of the screen
            // Only site names are shown here, never usernames or passwords
            listBoxPasswords.FormattingEnabled = true;
            listBoxPasswords.ItemHeight = 15;
            listBoxPasswords.Location = new Point(310, 25);
            listBoxPasswords.Name = "listBoxPasswords";
            listBoxPasswords.Size = new Size(250, 184);
            listBoxPasswords.TabIndex = 6;

            // ---- Site Label ----
            // The text that says "Site:" next to the site input box
            lblSite.AutoSize = true;
            lblSite.Location = new Point(20, 28);
            lblSite.Name = "lblSite";
            lblSite.Size = new Size(29, 15);
            lblSite.TabIndex = 7;
            lblSite.Text = "Site:";

            // ---- Username Label ----
            // The text that says "Username:" next to the username input box
            lblUsername.AutoSize = true;
            lblUsername.Location = new Point(20, 58);
            lblUsername.Name = "lblUsername";
            lblUsername.Size = new Size(63, 15);
            lblUsername.TabIndex = 8;
            lblUsername.Text = "Username:";

            // ---- Password Label ----
            // The text that says "Password:" next to the password input box
            lblPassword.AutoSize = true;
            lblPassword.Location = new Point(20, 88);
            lblPassword.Name = "lblPassword";
            lblPassword.Size = new Size(60, 15);
            lblPassword.TabIndex = 9;
            lblPassword.Text = "Password:";

            // ---- Delete Entry Button ----
            // Clicking this permanently removes the selected entry from the vault
            btnDelete.Location = new Point(220, 123);
            btnDelete.Name = "btnDelete";
            btnDelete.Size = new Size(55, 55);
            btnDelete.TabIndex = 10;
            btnDelete.Text = "Delete Entry";
            btnDelete.UseVisualStyleBackColor = true;
            btnDelete.Click += btnDelete_Click;

            // ---- Form Settings ----
            // Set the default background colour before the theme is applied
            BackColor = Color.DarkGray;

            // Set the overall size of the main vault window
            ClientSize = new Size(600, 220);

            // Add all controls to the form so they actually appear on screen
            Controls.Add(btnDelete);
            Controls.Add(lblPassword);
            Controls.Add(lblUsername);
            Controls.Add(lblSite);
            Controls.Add(listBoxPasswords);
            Controls.Add(btnChangePassword);
            Controls.Add(btnView);
            Controls.Add(btnAdd);
            Controls.Add(txtPassword);
            Controls.Add(txtUsername);
            Controls.Add(txtSite);
            Name = "MainForm";
            Text = "Password Manager";

            // Resume the layout engine now everything is configured
            ResumeLayout(false);
            PerformLayout();
        }

        // Declare all controls as private fields so they can be
        // accessed from anywhere in the MainForm class
        private System.Windows.Forms.TextBox txtSite;
        private System.Windows.Forms.TextBox txtUsername;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.Button btnView;
        private System.Windows.Forms.Button btnChangePassword;
        private System.Windows.Forms.ListBox listBoxPasswords;
        private System.Windows.Forms.Label lblSite;
        private System.Windows.Forms.Label lblUsername;
        private System.Windows.Forms.Label lblPassword;
        private Button btnDelete;
    }
}
