// This file is automatically generated by Visual Studio when you design the form visually
// It creates and positions all the labels, textbox and buttons on the view password screen
// Do not edit this file manually as Visual Studio will overwrite your changes

namespace SecureVault
{
    partial class ViewPasswordForm
    {
        // Keeps track of all components so they can be cleaned up when the form closes
        private System.ComponentModel.IContainer components = null;

        // Runs automatically when the form closes to free up memory
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            // Create all the controls that appear on the view password screen
            lblSiteTitle = new Label();
            lblUsernameTitle = new Label();
            lblPasswordTitle = new Label();
            lblSecurityTitle = new Label();
            lblSite = new Label();
            lblUsername = new Label();
            txtPassword = new TextBox();
            btnToggleVisibility = new Button();
            btnCopyPassword = new Button();
            btnClose = new Button();
            lblSecurityStatus = new Label();

            // Pause layout while we set everything up
            SuspendLayout();

            // ---- Site Title Label ----
            // The static text that says "Site :" on the left side
            lblSiteTitle.AutoSize = true;
            lblSiteTitle.Location = new Point(166, 91);
            lblSiteTitle.Name = "lblSiteTitle";
            lblSiteTitle.Size = new Size(32, 15);
            lblSiteTitle.TabIndex = 0;
            lblSiteTitle.Text = "Site :";

            // ---- Username Title Label ----
            // The static text that says "Username :" on the left side
            lblUsernameTitle.AutoSize = true;
            lblUsernameTitle.Location = new Point(166, 115);
            lblUsernameTitle.Name = "lblUsernameTitle";
            lblUsernameTitle.Size = new Size(66, 15);
            lblUsernameTitle.TabIndex = 1;
            lblUsernameTitle.Text = "Username :";

            // ---- Password Title Label ----
            // The static text that says "Password :" on the left side
            lblPasswordTitle.AutoSize = true;
            lblPasswordTitle.Location = new Point(166, 144);
            lblPasswordTitle.Name = "lblPasswordTitle";
            lblPasswordTitle.Size = new Size(63, 15);
            lblPasswordTitle.TabIndex = 2;
            lblPasswordTitle.Text = "Password :";

            // ---- Security Title Label ----
            // The static text that says "Security :" on the left side
            lblSecurityTitle.AutoSize = true;
            lblSecurityTitle.Location = new Point(166, 171);
            lblSecurityTitle.Name = "lblSecurityTitle";
            lblSecurityTitle.Size = new Size(55, 15);
            lblSecurityTitle.TabIndex = 3;
            lblSecurityTitle.Text = "Security :";

            // ---- Site Value Label ----
            // This shows the actual site name, populated from the entry data
            lblSite.AutoSize = true;
            lblSite.Location = new Point(240, 91);
            lblSite.Name = "lblSite";
            lblSite.Size = new Size(0, 15);
            lblSite.TabIndex = 4;

            // ---- Username Value Label ----
            // This shows the actual username, populated from the entry data
            lblUsername.AutoSize = true;
            lblUsername.Location = new Point(240, 115);
            lblUsername.Name = "lblUsername";
            lblUsername.Size = new Size(0, 15);
            lblUsername.TabIndex = 5;

            // ---- Password TextBox ----
            // This shows the password, hidden behind dots by default
            // ReadOnly means the user cannot type in or edit it
            // ShortcutsEnabled = false prevents copying via keyboard shortcuts
            txtPassword.Location = new Point(240, 141);
            txtPassword.Name = "txtPassword";
            txtPassword.ReadOnly = true;
            txtPassword.ShortcutsEnabled = false;
            txtPassword.Size = new Size(114, 23);
            txtPassword.TabIndex = 6;
            txtPassword.TabStop = false;
            txtPassword.UseSystemPasswordChar = true;

            // ---- Toggle Visibility Button ----
            // Clicking this shows or hides the password for 10 seconds
            btnToggleVisibility.Location = new Point(146, 219);
            btnToggleVisibility.Name = "btnToggleVisibility";
            btnToggleVisibility.Size = new Size(75, 23);
            btnToggleVisibility.TabIndex = 8;
            btnToggleVisibility.Text = "Show ";
            btnToggleVisibility.UseVisualStyleBackColor = true;
            btnToggleVisibility.Click += btnToggleVisibility_Click;

            // ---- Copy Password Button ----
            // Clicking this copies the password to the clipboard
            // The clipboard will be cleared automatically after 15 seconds
            btnCopyPassword.Location = new Point(240, 219);
            btnCopyPassword.Name = "btnCopyPassword";
            btnCopyPassword.Size = new Size(114, 23);
            btnCopyPassword.TabIndex = 9;
            btnCopyPassword.Text = "Copy Password ";
            btnCopyPassword.UseVisualStyleBackColor = true;
            btnCopyPassword.Click += btnCopyPassword_Click;

            // ---- Close Button ----
            // Clicking this runs SecureCleanup and closes the form
            btnClose.Location = new Point(375, 219);
            btnClose.Name = "btnClose";
            btnClose.Size = new Size(75, 23);
            btnClose.TabIndex = 10;
            btnClose.Text = "Close";
            btnClose.UseVisualStyleBackColor = true;
            btnClose.Click += btnClose_Click;

            // ---- Security Status Label ----
            // This shows the clipboard countdown message after copying
            lblSecurityStatus.AutoSize = true;
            lblSecurityStatus.Location = new Point(240, 171);
            lblSecurityStatus.Name = "lblSecurityStatus";
            lblSecurityStatus.Size = new Size(0, 15);
            lblSecurityStatus.TabIndex = 11;

            // ---- Form Settings ----
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;

            // Set the overall size of the view password window
            ClientSize = new Size(592, 345);

            // Add all controls to the form so they appear on screen
            Controls.Add(lblSecurityStatus);
            Controls.Add(btnClose);
            Controls.Add(btnCopyPassword);
            Controls.Add(btnToggleVisibility);
            Controls.Add(txtPassword);
            Controls.Add(lblUsername);
            Controls.Add(lblSite);
            Controls.Add(lblSecurityTitle);
            Controls.Add(lblPasswordTitle);
            Controls.Add(lblUsernameTitle);
            Controls.Add(lblSiteTitle);
            Name = "ViewPasswordForm";
            Text = "View Entry";

            // Resume the layout engine now everything is configured
            ResumeLayout(false);
            PerformLayout();
        }

        // Declare all controls as private fields so they can be
        // accessed from anywhere in the ViewPasswordForm class
        private Label lblSiteTitle;
        private Label lblUsernameTitle;
        private Label lblPasswordTitle;
        private Label lblSecurityTitle;
        private Label lblSite;
        private Label lblUsername;
        private TextBox txtPassword;
        private Button btnToggleVisibility;
        private Button btnCopyPassword;
        private Button btnClose;
        private Label lblSecurityStatus;
    }
}
